studassweb/base/urls.py
# coding=utf-8
from django.conf.urls import url

from . import ajax
from . import views

urlpatterns = [
    url('^ajax/give_feedback$',
        ajax.give_feedback,
        name='base_ajax_give_feedback'),

    url('^changelog$',
        views.view_change_log,
        name='base_changelog'),
]

studassweb/events/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import AddEventItemView, EditEventItemView, DeleteEventItemView, ListEventItemsView, \
    DeleteEventSignupByCodeView

from . import views
slug_pattern = '(?P<slug>[-\w\d]+)'


urlpatterns = [
    url(r'^$', views.home, name='events_home'),

    # url(r'^event/(?P<event_id>\d+)/$',
    #    views.event_detail',
    #    name='events_view_event'),

    url(r'^event/%s/$' % slug_pattern,
        views.view_event,
        name='events_view_event'),
    url(r'^event/(?P<event_id>\d+)/edit_signup_by_id/(?P<signup_id>\d+)$',
        views.view_event,
        name='events_view_event_edit_signup_by_id'),
    url(r'^event/(?P<event_id>\d+)/edit_signup_by_code/(?P<auth_code>[a-z0-9]{32})$',
        views.view_event,
        name='events_view_event_edit_signup_by_code'),

    url(r'^add/$', views.add_edit_event, name='events_add_event'),
    url(r'^edit/(?P<event_id>\d+)/$', views.add_edit_event, name='events_edit_event'),
    url(r'^delete/(?P<event_id>\d+)/$', views.delete_event, name='events_delete_event'),
    url(r'^delete_signup/(?P<event_signup_id>\d+)/$',
        views.delete_event_signup,
        name='events_delete_event_signup'),
    url(r'^delete_signup/(?P<auth_code>[a-z0-9]{32})$',
        DeleteEventSignupByCodeView.as_view(),
        name='events_delete_event_signup_by_code'),
    url(r'^add_event_item/$', AddEventItemView.as_view(), name='events_add_eventitem'),
    url(r'^edit_event_item/(?P<pk>\d+)/$', EditEventItemView.as_view(), name='events_edit_eventitem'),
    url(r'^delete_event_item/(?P<pk>\d+)/$', DeleteEventItemView.as_view(), name='events_delete_eventitem'),
    url(r'^list_event_items/$', ListEventItemsView.as_view(), name='events_list_eventitems'),
]

studassweb/studassweb/urls.py
# coding=utf-8
from django.conf.urls import include, url
from django.contrib import admin
from base.utils import get_modules_with
from django.conf import settings
from django.conf.urls.static import static
from django.db.utils import OperationalError

from frontpage import views

import logging

logger = logging.getLogger(__name__)

urlpatterns = [
    url(r'^$', views.frontpage, name='frontpage_home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.MEDIA_DJANGO:
    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.10/howto/static-files/
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add the urlpatterns of all modules
for mod, url_func in get_modules_with("register", "get_urls"):
    # recent django versions run this code before initing the DB, so we have to catch the failure of the settings module
    try:
        for url_pattern in url_func():
            urlpatterns.append(url(url_pattern, include(mod + ".urls")))
    except OperationalError:
        logger.warning("URL loading failed for module '" + mod + "' because the database hasn't been set up yet")

studassweb/base/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
import json
import os
import datetime
import re
from concurrent import futures
from urllib.request import urlopen, Request
from urllib.error import HTTPError
import logging
from solo.models import SingletonModel
from .utils import get_all_modules, get_modules_with
from string import ascii_letters, digits


logger = logging.getLogger(__name__)

THEME_DIR = os.path.join("css", "bootswatch_themes")

CSS_OVERRIDE_FILE_PATH = os.path.join(settings.STATIC_DIR,
                                      "css",
                                      "base",
                                      "override.css")


class CSSOverrideFile(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=200, default="")

    def get_latest_content(self):
        """

        :return:
        """
        try:
            return CSSOverrideContent.objects.filter(file=self).first()
        except CSSOverrideContent.DoesNotExist:
            return None

    def get_absolute_url(self):
        """

        :return:
        """
        return reverse("base_settings_edit_css_file",
                       kwargs={'file_id': self.id})

    def __str__(self):
        return self.name


class CSSOverrideContent(models.Model):
    file = models.ForeignKey(CSSOverrideFile, on_delete=models.CASCADE)
    css = models.TextField()
    author = models.ForeignKey(User, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self):
        return self.file.name + " [" + str(self.timestamp) + "]"


class BootswatchTheme(models.Model):
    name = models.CharField(max_length=50, unique=True)
    bs_css_url = models.URLField(max_length=200)
    preview_image_url = models.URLField()
    preview_url = models.URLField()

    def __str__(self):
        return self.name

    @classmethod
    def create_from_json(cls, json_dict):
        """
        Parses the theme data from the JSON
        :param json_dict:
        :return:
        """

        try:
            # update old entry if it exists
            bst = cls.objects.get(name=json_dict['name'])
            bst.bs_css_url = json_dict['cssMin']
            bst.preview_image_url = json_dict['thumbnail']
            bst.preview_url = json_dict['preview']
        except cls.DoesNotExist:
            # otherwise create a new one
            bst = BootswatchTheme(name=json_dict['name'],
                                  bs_css_url=json_dict['cssMin'],
                                  preview_image_url=json_dict['thumbnail'],
                                  preview_url=json_dict['preview'])

        return bst.save()


THEME_DEFAULT_CSS = "css/bootstrap.min.css"
THEME_DEFAULT_CSS_MOD = "css/bootstrap-theme.min.css"


class SiteConfiguration(SingletonModel):
    association_name = models.CharField(max_length=100, default='Site name')
    base_url = models.CharField(max_length=150, default='http://localhost:8000')
    association_contact_email = models.EmailField(max_length=254, default='example@example.com')
    association_founded = models.IntegerField(default=1900)
    # main bootstrap theme css file
    bootstrap_theme_url = models.CharField(max_length=200, default=THEME_DEFAULT_CSS)
    # optional theme modifier css file
    bootstrap_theme_mod_url = models.CharField(max_length=200, null=True, blank=True, default=THEME_DEFAULT_CSS_MOD)
    bootswatch_version = models.CharField(max_length=50, default=None, null=True)
    bootswatch_last_checked = models.DateTimeField(default=timezone.datetime(year=2000, month=1, day=1))

    show_feedback_helptext = models.BooleanField(default=True)

    current_css_override = models.ForeignKey(CSSOverrideContent, null=True, default=None)

    @classmethod
    def instance(cls):
        """

        :return:
        """
        obj, created = cls.objects.get_or_create()
        return obj

    @classmethod
    def founded(cls):
        """

        :return: The year this association was founded
        """
        return cls.instance().association_founded

    @classmethod
    def update_bootswatch(cls):
        """
        Updates bootswatch if it's outdated
        :return:
        """
        instance = cls.instance()
        if instance.bootswatch_version:
            updated_ago = timezone.now() - instance.bootswatch_last_checked
            # Don't check for updates more often than once a week
            if updated_ago < datetime.timedelta(weeks=1):
                return
        cls._update_bootswatch()

    @classmethod
    def _update_bootswatch(cls):
        try:
            r = Request(url="http://api.bootswatch.com/3/")
            r.add_header('User-Agent', 'SAW')
            data = urlopen(r).read().decode()
        except HTTPError:
            logger.error("Failed to fetch bootswatch theme descriptor %s")
            return
        data_dict = json.loads(data)
        logger.debug(data_dict)
        version = data_dict['version']
        with futures.ThreadPoolExecutor(max_workers=16) as executor:
            for theme_data in data_dict['themes']:
                executor.submit(BootswatchTheme.create_from_json, theme_data)

        instance = cls.instance()
        instance.bootswatch_version = version
        instance.bootswatch_last_checked = timezone.datetime.now()
        instance.save()

    @classmethod
    def set_css_override(cls, override):
        """
        Saves the text of the override to the static override file.
        if override is None, clear the file.
        :param override:
        :return:
        """
        instance = cls.instance()
        instance.current_css_override = override
        instance.save()
        # ensure that the directory exists
        if not os.path.exists(os.path.dirname(CSS_OVERRIDE_FILE_PATH)):
            os.makedirs(os.path.dirname(CSS_OVERRIDE_FILE_PATH))
        # overwrite the old file
        with open(CSS_OVERRIDE_FILE_PATH, "w") as f:
            if override is not None:
                f.write(override.css)

    @classmethod
    def get_css_override(cls):
        """

        :return:
        """
        return cls.instance().current_css_override


class DisabledModule(models.Model):
    app_name = models.CharField(max_length=50, unique=True)

    @classmethod
    def is_disabled(cls, name):
        """

        :param name:
        :return:
        """
        return cls.objects.filter(app_name=name).exists()

    @classmethod
    def is_enabled(cls, name):
        """

        :param name:
        :return:
        """
        return not cls.is_disabled(name)

    @classmethod
    def disable(cls, name):
        """

        :param name:
        """
        try:
            cls.objects.get(app_name=name)
            # if it exists do nothing
        except cls.DoesNotExist:
            # if it doesn't, add it
            mod = DisabledModule(app_name=name)
            mod.save()

    @classmethod
    def enable(cls, name):
        """

        :param name:
        """
        try:
            mod = cls.objects.get(app_name=name)
            mod.delete()
        except cls.DoesNotExist:
            # Nothing to be done
            pass

    @classmethod
    def get_all_enabled_modules(cls):
        """

        :return:
        """
        all_modules = get_all_modules()
        return [mod for mod in all_modules if cls.is_enabled(mod)]

    @classmethod
    def execute_for_all_enabled(cls, module, func_name):
        """
        execute the specified function from the specified module in all enabled apps where it exists
        :return:
        """
        mod_funcs = get_modules_with(module, func_name)

        for mod, func in mod_funcs:
            if cls.is_enabled(mod):
                func()


class Comment(models.Model):
    text = models.TextField(max_length=400)
    created = models.DateTimeField('Date created', auto_now_add=True)
    author = models.ForeignKey(User)

    # A generic field for linking to any model
    _content_type = models.ForeignKey(ContentType)
    _object_id = models.PositiveIntegerField()
    target = GenericForeignKey('_content_type', '_object_id')

    class Meta:
        ordering = ("_object_id", "created")

    def set_target(self, target):
        """
        :param target: A Django Model
        :return:
        """
        self._content_type = ContentType.objects.get_for_model(target)
        self._object_id = target.id

    @classmethod
    def get_comments_for_object(cls, obj):
        """

        :param obj:
        :return:
        """
        content_type = ContentType.objects.get_for_model(obj)
        return cls.objects.filter(_content_type=content_type, _object_id=obj.id)

    def __str__(self):
        return "%s#%s" % (self.target, self.id)


class Feedback(models.Model):
    FEEDBACK_HELPTEXT = "HELPTEXT"
    FEEDBACK_CHOICES = (
        (FEEDBACK_HELPTEXT, "Help text feedback"),
    )
    RESPONSE_GOOD = "GOOD"
    RESPONSE_BAD = "BAD"
    RESPONSE_UNNECESSARY = "UNNE"
    RESPONSE_CHOICES = (
        (RESPONSE_GOOD, "Good"),
        (RESPONSE_BAD, "Bad"),
        (RESPONSE_UNNECESSARY, "Unnecessary"),
    )

    user = models.ForeignKey(User, blank=True, null=True)
    url = models.CharField(max_length=300)
    ip_address = models.GenericIPAddressField()
    type = models.CharField(max_length=10, choices=FEEDBACK_CHOICES)
    response = models.CharField(max_length=10, choices=RESPONSE_CHOICES)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (

studassweb/base/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import DummyForm
from django.conf import settings

def delete_confirmation_view(request, item, form_url, redirect_url,
                             template="base/delete_confirmation.html"):
    """

    :param request:
    :param item:
    :param form_url:
    :param redirect_url:
    :param template:
    :return:
    """
    form = DummyForm(request.POST or None)
    item_name = str(item)
    if form.is_valid():
        item.delete()
        if redirect_url:
            return HttpResponseRedirect(redirect_url)
        else:
            form = None
    context = {'form': form,
               'item': item,
               'form_url': form_url,
               'item_name': item_name}
    return render(request, template, context)


def view_change_log(request):
    """
    Show the change log
    :param request:
    :return:
    """
    context = {'saw_version'}
    return render(request, "base/changelog.html")

studassweb/events/templates/events/add_edit_event.html
{% extends "events/base.html" %}

{% load i18n %}
{% load bootstrap3 %}
{% load static %}
{% load sidemenu %}
{% load cssmap %}

{% block breadcrumb2 %}
    <li class="active">
        {% if form.instance.pk %}
            {% trans "Editing" %}
            {{ form.instance.title }}
        {% else %}
            {% trans "New Event" %}
        {% endif %}
    </li>
{% endblock %}


{% block main_content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        {% bootstrap_form form_items %}
        {% buttons %}
            <button type="submit" class="{% get_css "sawbutton_save" %}">
                {% trans "Submit" %}
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

{% block scripts %}
    <link rel="stylesheet" type="text/css" href="{% static "css/base/jquery.datetimepicker.css" %}"/>
    <script src="{% static "js/base/jquery.datetimepicker.js" %}"></script>
    <script type="text/javascript">
        $(function () {

            //Set up datetimepicker
            $( "#{{ form.signup_start.id_for_label }}" ).datetimepicker({
                dayOfWeekStart: 1,
                format: "d.n.Y H:i"
            });
            $( "#{{ form.signup_deadline.id_for_label }}" ).datetimepicker({
                dayOfWeekStart: 1,
                format: "d.n.Y H:i"
            });
            $( "#{{ form.start.id_for_label }}" ).datetimepicker({
                dayOfWeekStart: 1,
                format: "d.n.Y H:i"
            });
            $( "#{{ form.stop.id_for_label }}" ).datetimepicker({
                dayOfWeekStart: 1,
                format: "d.n.Y H:i"
            });
        })
    </script>
{% endblock %}

{% block extrabuttons_in_panel5 %}
    {% if form.instance.pk %}
        <form action="{% url 'events_delete_event' form.instance.pk %}" method="post" onclick="return confirm('{% trans "Are you sure?" %}')">
            {% csrf_token %}
            <button type="submit" class="{% get_css "sawbutton_delete" %} btn-block">
                {% trans "Remove this event" %}
            </button>
        </form>
    {% endif %}
{% endblock %}

{% block sidebar-panel-help %}
    {% sidebarpanel "help" %}
        {% trans "Help" %}
        {% body %}
        <p>{% trans "This is where you create events." %}</p>
        <p>{% trans "All fields except for event items are required by default." %}</p>
    {% endsidebarpanel %}
{% endblock %}

studassweb/events/templates/events/archive.html
{% extends "events/base.html" %}

{% load i18n %}
{% load bootstrap3 %}

studassweb/events/templates/events/base.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load sawp %}
{% load sidemenu %}
{% load cssmap %}

{% block title %}
    {% trans "Events" %}
{%  endblock %}

{% block menu %}
    {% load dynamic_menu %}
    {% display_menu "main_menu" "Events" %}
{% endblock %}

{% block breadcrumb1 %}
    <li><a href="{% url "events_home" %}">
        {% trans "Events" %}
    </a></li>
{% endblock %}



{% block sidebar-panel5 %}
    {% has_perm "events" "CAN_CREATE_EVENTS" as can_create_events %}
    {% if can_create_events%}
        {% sidebarpanel "vertical_buttons" %}
            {% trans "Actions" %}
            {% body %}
            {% block extrabuttons_in_panel5 %}{% endblock %}
            {% block add_new_event %}
                <a href="{% url 'events_add_event' %}" class="{% get_css "sawbutton_sidebar" %}">
                    {% trans "Add new event" %}
                </a>
            {% endblock %}
            {% block configure_event_items %}
                <a href="{% url 'events_list_eventitems' %}" class="{% get_css "sawbutton_sidebar" %}">
                    {% trans "Configure event items" %}
                </a>
            {% endblock %}
        {% endsidebarpanel %}
    {% endif %}
{% endblock%}

studassweb/events/templates/events/eventitem_form.html
{% extends "events/base.html" %}

{% load i18n %}
{% load bootstrap3 %}
{% load sawp %}
{% load sidemenu %}
{% load cssmap %}

{% block breadcrumb2 %}
    <li class="active">
        <a href="{% url "events_list_eventitems" %}">{% trans "List items " %}</a>
    </li>
{% endblock %}

{% block breadcrumb3 %}
    <li class="inactive">
        {% if form.instance.pk %}
            {% trans "Edit event item" %}
        {% else %}
            {% trans "Add event item" %}
        {% endif %}
    </li>
{% endblock %}

{% block main_content %}

    <form action="" method="post">{% csrf_token %}

        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="{% get_css "sawbutton_save" %}">
                {% if form.instance.pk %}
                    {% trans "Update" %}
                {% else %}
                    {% trans "Add" %}
                {% endif %}
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

{% block sidebar-panel5 %}{% endblock %}

{% block sidebar-panel-help %}
    {% sidebarpanel "help" %}
        {% trans "Help" %}
        {% body %}
        <p>{% trans "This is where you create custom event items for later use." %}</p>
        <p>{% trans "You can define a datatype for each event item. The datatype defines the type of input that is accepted " %}</p>
        <p>{% trans "Don't worry, you can edit event items later." %}</p>
    {% endsidebarpanel %}
{% endblock %}

studassweb/events/templates/events/eventitem_list.html
{% extends "events/base.html" %}

{% load i18n %}
{% load bootstrap3 %}
{% load sawp %}
{% load sidemenu %}
{% load cssmap %}

{% block breadcrumb2 %}
    <li class="active">
        <a href="{% url "events_list_eventitems" %}">{% trans "List items " %}</a>
    </li>
{% endblock %}

{% block main_content %}
    <div class="table-responsive">
        <table class="table table-striped">
            <tbody>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Type" %}</th>
                <th>{% trans "Required" %}</th>
                <th>{% trans "Public" %}</th>
                <th>{% trans "Hidden in print view" %}</th>
                <th>{% trans "Action" %}</th>
            </tr>
            {% for eitem in object_list %}
                <tr>
                    <td>
                        {{ eitem.name }}
                    </td>
                    <td>
                        {{ eitem.get_type_display }}
                    </td>
                    <td>
                        {% if eitem.required == True %}
                            <span class="glyphicon glyphicon-check" aria-label="True"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-unchecked" aria-label="False"></span>
                        {% endif %}
                    </td>
                    <td>
                        {% if eitem.public == True %}
                            <span class="glyphicon glyphicon-check" aria-label="True"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-unchecked" aria-label="False"></span>
                        {% endif %}
                    </td>
                    <td>
                        {% if eitem.hide_in_print_view == True %}
                            <span class="glyphicon glyphicon-check" aria-label="True"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-unchecked" aria-label="False"></span>
                        {% endif %}
                    </td>
                    <td>
                        <a class="{% get_css "sawbutton_main" %}" href="{% url "events_edit_eventitem" eitem.id %}">
                            {% trans "Edit" %}
                        </a>
                        <form action="{% url "events_delete_eventitem" eitem.id %}" method="post"
                              onclick="return confirm('{% trans "Are you sure?" %}');">
                            {% csrf_token %}
                            <input type="submit" value="{% trans "Delete" %}"
                                   class="{% get_css "sawbutton_delete" %}" />
                        </form>
                    </td>
                </tr>
                {% empty %}

                <tr>
                    <td>
                        {% trans "No event items added yet!" %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}



{% block extrabuttons_in_panel5 %}
    <a href="{% url 'events_add_eventitem' %}" class="{% get_css "sawbutton_main" %}">
        {% trans "Add new event item" %}
    </a>
{% endblock%}

{% block configure_event_items %}{% endblock %}

{% block sidebar-panel-help %}
    {% sidebarpanel "help" %}
        {% trans "Help" %}
        {% body %}
        <p>{% trans "This is where you create custom event items" %}</p>
    {% endsidebarpanel %}
{% endblock %}

studassweb/events/templates/events/frontpage_content.html
{% load i18n %}

{% if events.count > 0 %}
    <ul style="list-style-type:disc; padding-left: 10px;">
        {% for event in events.list %}
            <li>
                <a href="{{ event.get_absolute_url }}">
                    {{ event.title }}
                </a>
                    {% now "Y" as today_year %}
                    {% if event.start|date:"Y" != today_year %}
                        ({{ event.start | date:"j N"}} {{ event.start.year }})
                    {% else %}
                        ({{ event.start | date:"j N"}})
                    {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    {% trans "There are no upcoming events" %}.
{% endif %}

studassweb/events/templates/events/view_events.html
{% extends "events/base.html" %}

{% load i18n %}
{% load bootstrap3 %}
{% load sawp %}
{% load sidemenu %}
{% load cssmap %}

{% block breadcrumb1 %}
    <li class="active">
        {% trans "Events" %}
    </li>
{% endblock %}

{% block main_content %}
    <h3>{% trans "Events" %}</h3>
    {% for event in events %}
        <div class="{% get_css "sawpanel_main" %}">
            <div class="panel-heading">

                <h4>
                    <a class="h3" href="{{ event.get_absolute_url }}">
                        {{ event.start|date:"Y-m-d" }} {{ event.title }}
                    </a>
                </h4>

            </div>
            <div class="panel-body">
                {{ event.get_summary|safe }}
            </div>
        </div>
        {% empty %}
        <p>{% trans "No events found!" %}</p>
    {% endfor %}


{% endblock %}

{% block sidebar-panel-help %}
    {% has_perm "events" "CAN_CREATE_EVENTS" as show_help %}
    {% if show_help %}
        {% sidebarpanel "help" %}
            {% trans "Help" %}
            {% body %}
            <p>{% trans "Here you can see available events." %}</p>
            <p>{% trans "Event items are custom fields for signup. They can make your event easier to manage." %}</p>
        {% endsidebarpanel %}
    {% endif %}
{% endblock %}